apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    version: 1
    editable: false

    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      prometheusVersion: 3.13.2
      timeInterval: 15s

